{
  "correctText": "Пока нет никаких данных , свидетельствующих о том , что это не было несчастным  случаем , а являлось чьим-то злым умыслом .",
  "errors": [
    {
      "correctReplacement": "умыслом",
      "type": "case",
      "wordNumber": 20
    }
  ],
  "textWithError": "Пока нет никаких данных , свидетельствующих о том , что это не было несчастным случаем , а являлось чьим-то злым умыслу ."
}